s3_list_url: "https://s3.amazonaws.com/capitalbikeshare-data?list-type=2"
s3_object_url: "https://s3.amazonaws.com/capitalbikeshare-data/{key}"

gbfs_station_information_url: "https://gbfs.lyft.com/gbfs/1.1/dca-cabi/en/station_information.json"

supported_output_formats:
  - print
  - dict
  - json

backend_extensions:
  sqlite:
    - .db
    - .sqlite
    - .sqlite3

manifest_table_name: "manifest"

column_renames:
  trips_raw_data:
    ride_id: ride_id
    Bike number: rideable_type
    rideable_type: rideable_type
    started_at: started_at
    Start date: started_at
    ended_at: ended_at
    End date: ended_at
    start_station_name: start_station_name
    Start station: start_station_name
    Start station number: start_station_id
    start_station_id: start_station_id
    end_station_name: end_station_name
    End station: end_station_name
    End station number: end_station_id
    end_station_id: end_station_id
    start_lat: start_lat
    start_lng: start_lng
    end_lat: end_lat
    end_lng: end_lng
    member_casual: member_casual
    Member type: member_casual
    Duration : duration